name: banana_flutter_app
description: Flutter skeleton for Banana mobile app.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  dio:
  flutter_riverpod:
  flutter_secure_storage:
  gal:
  go_router:
  http_parser:
  shared_preferences:
  cached_network_image:
  image_gallery_saver:
  image_picker:
  path_provider:
  permission_handler:
  photo_view:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
